name: Release Nightly

on: # 顶格
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  bundle-mac:
    name: Create a macOS bundle
    runs-on: macos-latest

    steps:
      # ---------------- checkout ----------------
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false

      # ---------------- Rust cache ----------------
      - name: Cache cargo registry + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # ---------------- Node (optional) cache ----
      - name: Cache node_modules
        if: hashFiles('**/package-lock.json') != ''
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # ---------------- Install toolchains -------
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # （若你需要 Rustup，可加 setup‑rust）

      # ---------------- 其他自定义步骤 ------------
      - name: Set release channel to nightly
        run: |
          set -eu
          version=$(git rev-parse --short HEAD)
          echo "Publishing version: ${version} on release channel nightly"
          echo "nightly" > crates/zed/RELEASE_CHANNEL

      - name: Create macOS app bundle
        run: |
          cargo build --release


      - name: Upload Zed Nightly
        run: script/upload-nightly macos
